-- Structure manuelle de comparaison, distincte de la table ORM du sprint 5.
CREATE TABLE IF NOT EXISTS etudiants_manuels (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR NOT NULL,
    prenom VARCHAR NOT NULL,
    age INTEGER NOT NULL,
    email VARCHAR NOT NULL,
    telephone VARCHAR NULL
);
